### ISSUE TITLE
Add weekly report

### ISSUE THREAD

**Issue by npvinhsd** [psucodervn/sheets#4]

**Comment by ngoctint1lvc** [comment]
We should implement this feature as soon as possible!

**Comment by psucodervn** [comment]
Which information should we show in the weekly report?

**Comment by npvinhsd** [comment]
> Which information should we show in the weekly report?

Some imformation we used in current report like the current issue we are working in the week, total point

**Comment by psucodervn** [comment]
@npvinhsd @ngoctint1lvc I've deployed the very first version of weekly report feature. Please have a look at this: https://sheet.hungle.dev/report?from=20-04-2020
